---
- hosts: all
  tasks:

  - name: copy dockerfile into Remote machine
    copy:
     src: dockerfile
     dest: .

  - name: copy .war file into Remote machine
    copy:
     src: webapp.war
     dest: .

  - name: stop the running container
    command: docker stop customcontainer
    ignore_errors: True

  - name: remove  the running container
    command: docker rm customcontainer
    ignore_errors: True

  - name: remove  the running image
    command: docker rmi  customimage
    ignore_errors: True

  - name: create customimage from dockerfile 
    command: docker build -t customimage .
     
  - name: create and run container
    command: docker run -d -p 8080:8080 --name customcontainer customimage


